### ISSUE TITLE
Can't install package via NuGet from VS2013

### ISSUE THREAD

**Issue by neilyoung** [RMCKirby/ColorConsole#1]
Complains about invalid data structures in zip.

PM> Install-Package ColorConsole
Install-Package : ZIP archive contains unsupported data structures.
At line:1 char:16
- Install-Package <<<<  ColorConsole
  - CategoryInfo          : NotSpecified: (:) [Install-Package], NotSupportedException
  - FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by rmckirby** [comment]
Hi Neil, thanks for raising this issue. I have just been looking into this and can't seem to find a reason as to why this would happen.

I develop on Ubuntu via mono and use `Paket` rather than `Nuget` so I am unable to use `VS2013` and replicate your environment.

I have tested the install with both `Paket` and `Nuget` from the command line:

`mono .nuget.exe install ColorConsole` works fine

As does the integrated `MonoDevelop` package manager.

I did a quick google search and found the [following](http://stackoverflow.com/questions/8314400/nuget-add-reference-error-while-installing-packages)

Could you confirm whether this solves the issue or not?

Thanks,

Richard

**Comment by neilyoung** [comment]
Hi Richard thanks for the quick follow up.I will do the check tomorrow and let you know.
Regards

Sent from my iPhone
